##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_pod_rules_plugin
description: Linter rules for xyz_pod
repository: https://github.com/robmllze/xyz_pod_rules_plugin
version: 0.1.0

## -----------------------------------------------------------------------------
environment:
  sdk: ">= 3.3.1 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  analyzer: ^6.4.1
  custom_lint_builder: ^0.6.4
